### ISSUE TITLE
Is there any sample for readDSCBChain() method?

### ISSUE THREAD

**Issue by simpleDgq** [zsystems/java-samples#3]
****
Hi, 

I want to read the DSCB for an extended address volume(EAV) data set, i find that I can use the readDSCBChain() to do it.
When I use this method, it returned the Format1DSCB DSCB anyway, I suppose that because there is no EAV data set in my environment.
As the JZOS document said that it would return all the DSCB chain for the data set. What’s the meaning of the DSCB chain? Could you please give me an example for the data for the EAV data set returned by this method?
Could you please give me an simple sample for the readDSCBChain() method? I can't find it in this repository.

Thanks.

**Comment by irisbaron** [comment]
@CarlosDGQ Dear Carlos, please see the response from the experts:

JZOS readDSCBChain javadoc refers to the DFSMSdfp publication for additional information:

   * The function and return codes for the OBTAIN / CAMLST-SEARCH macro 
    are described in the IBM publication <q>DFSMSdfp Advanced Services - SC26-7400</q>.

Here is a link to the documentation:
https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R3SC236861/$file/idas300_v2r3.pdf

Pages 22 to pages 25 describes DSCB Types and several examples illustrated with pictures. 

JZOS readDSCBchain returns a list of DSCBs associated with the dataset. Here is psedo code that demonstrates how to utilize the method and determines the type of each DCB in the returned chain:

		String[] volumes = ZFile.locateDSN(ssqDsn);
    		String vol = volumes[0];
    		DSCB[] dscbs = ZFile.readDSCBChain(ssqDsn, vol);
    		for (i = 0; i < dscbs.length; i++) {
 	   	     if (dscbs[i] instanceof Format1DSCB)
    			  // a Format1DSCB
    		     else if (dscbs[i] instanceof Format3DSCB)	
    			  // a Format3DSCB
    		     else if (dscbs[i] instanceof Format8DSCB)	
    			  // a Format8DSCB
     		     else if (dscbs[i] instanceof Format9DSCB)	
    			  // a Format9DSCB
                        }

Hope above information helps!

**Comment by simpleDgq** [comment]
Hi,
Thanks for your help.  It's very useful to me. The problem has been resolved, I will close this issue.
